# PowerShell script to initialize git, create GitHub repo, push, create Heroku app, and deploy
# Prerequisites: gh (GitHub CLI) logged in, heroku CLI logged in, git installed.
param(
    [string]$githubRepoName = "newflask-cbtapp",
    [string]$githubPrivate = "true",
    [string]$herokuAppName = "",
    [string]$herokuRegion = "us",
    [string]$superadminPassword = ""
)

Write-Host "Starting deployment automation..."

# Initialize git if needed
if (-not (Test-Path .git)) {
    git init
    git add -A
    git commit -m "Initial commit"
} else {
    git add -A
    git commit -m "Prepare for remote deploy" -a || Write-Host "No changes to commit"
}

# Create GitHub repo using gh
$ghCreateArgs = @('repo','create',$githubRepoName)
if ($githubPrivate -eq 'true') { $ghCreateArgs += '--private' } else { $ghCreateArgs += '--public' }
$ghCreateArgs += '--source=.'
$ghCreateArgs += '--remote=origin'
$ghCreateArgs += '--push'

Write-Host "Creating GitHub repository (requires gh CLI authentication)..."
gh @ghCreateArgs

# Create Heroku app
if ([string]::IsNullOrEmpty($herokuAppName)) {
    Write-Host "Creating Heroku app (name autogenerated)..."
    heroku create --region $herokuRegion
} else {
    Write-Host "Creating Heroku app with name $herokuAppName"
    heroku create $herokuAppName --region $herokuRegion
}

# Ensure git push to heroku remote
Write-Host "Pushing to Heroku git remote..."
git push heroku HEAD:master

# Set SUPERADMIN_PASSWORD if provided
if (-not [string]::IsNullOrEmpty($superadminPassword)) {
    heroku config:set SUPERADMIN_PASSWORD=$superadminPassword
}

Write-Host "Deployment script finished. Check GitHub and Heroku dashboard for app status."
